### ISSUE TITLE
assettocorsasharedmemory.dll void

### ISSUE THREAD

**Issue by gptxever** [mdjarv/assettocorsasharedmemory#1]
hello all,
i need to use this project to comunicate with an external program...
my problem is that i downloaded both the .dll both the project to compile to get the .dll..
on both cases, i got a dll (14kB) but void (without function inside) and i cannot call it in my program..
i used other software to see inside the .dll but is empty...
do you now the reason?please help me is very important for me..

p.s....i created a real time project with the MMF file and work properly. thank for your help.

(i use labview to call the dll)

**Comment by mdjarv** [comment]
I'm on a linux machine at the moment so it's a bit difficult to verify, but from what I can see the DLL contains the symbols. 14k sounds about right, the previous version which I used myself for an early project was just above 13k.

What software did you use to look inside the DLL?

I built the DLL in Visual Studio 2012 using .NET 4.5, is that version of .NET installed on your machine?

I haven't used LabVIEW in over 10 years and back then it was for designing circuits so I can't really help you with that side of your problem.

**Comment by gptxever** [comment]
Hello...
i used "DLL export viewer 1.63" to see inside.
Even with a dos command from Windows XP "dump export" return a DLL without
function.
The same thing with Labview "call library function"...
The project work, but if compile the DLL i have 14kb DLL without function..

Yes i use Visual studio 2012 on Win 8 or Win 7.
I will check the .NET 4.5 but i thing i have.

I downloaded "assettocorsasharedmemory_master" and
"assettocorsasharedmemory_02"...not change...

Could you try to compile for me the dll and send me your version?
old and new (13kb and 14kb)

do you have any suggestion for me?

thank you very much your attention for me..

Regards..

2015-01-21 15:52 GMT+01:00 Mathias Djärv <notifications@github.com>:

**Comment by mdjarv** [comment]
I don't know why DLL export viewer won't show the contents of this DLL, but I have downloaded it from GitHub under Releases, and I had no problem adding this DLL as a reference to my project to get access to the AssettoCorsa class and its events as described in the readme of this project.

Make sure you use the DLL from the URL below:
https://github.com/mdjarv/assettocorsasharedmemory/releases/tag/v0.2

**Comment by gptxever** [comment]
Dear Mathias, i tried to know why i cannot read the DLL: i think labview
cannot interpret the C# DLL...and not support framework 4.5,
Labview 2013 support 3.5 and labview 2014 4.0..
but i used jetbrain and i  could see the DLL method...so on internet i
found another way (as node costructor) to call the function of C# library
by labview...and now WORK PROPERLY!!!

So, i thank you for your time and sorry for disturb you.
I would ask you just last thing:
on release 0.2, you updated more data than first versione or just fix code?

thank you again...
you have been very courteous.

Best regards.

2015-01-21 21:02 GMT+01:00 Mathias Djärv <notifications@github.com>:

**Comment by mdjarv** [comment]
Great to hear that you solved your problem, and sorry I couldn't be of more help but I am not familiar with LabVIEW and I don't code much in .NET / C# apart from this library so my experience is limited.

It was quite a while ago since I touched this code, but from what I can recall the step from 0.1 to 0.2 was just cleaning up and changing some strings to Unicode to parse them better, I don't think more telemetry was added.

Good luck in your project :)
