### ISSUE TITLE
Meters

### ISSUE THREAD

**Issue by theouteredge** [mdjarv/assettocorsasharedmemory#12]
Hey,

I've been using your library to try and graph the telemetry data so I can compare laps, do you know how to get calculate how many meters the car has travelled from the start/finish line?

Thanks.

**Comment by mdjarv** [comment]
Unfortunately I don't see any data available that would show or even help calculate distance traveled

**Comment by theouteredge** [comment]
I've worked this out myself using the Graphics.CarPosition data, if you work out the different between two of the vectors you get the meters. So I was working out total meters driven based on the sum of differences between each data point collected.

Thanks for your code btw, it's been very helpful :)

**Comment by mdjarv** [comment]
Happy to hear you managed to work things out yourself
